filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
- type: log
  paths:
    - /var/log/nginx/*.log

#output.elasticsearch:
# hosts: 'elasticsearch:9200'
#  username: '${ELASTICSEARCH_USERNAME:}'
#  password: '${ELASTICSEARCH_PASSWORD:}'


output.logstash:
  # The Logstash hosts
  hosts: "logstash:5044"

