apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: mohamedsaeed/cognitive:nginx
        ports:
        - containerPort: 80
        # volumeMounts:
        #   - name: nginx_logs
        #     mountPath: /var/log/nginx/

      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
        ports:
        - containerPort: 9200

      - name: kibana
        image: mohamedsaeed/cognitive:kibana
        ports:
        - containerPort: 5601

      - name: logstash
        image: mohamedsaeed/cognitive:logstash
        ports:
        - containerPort: 9600
        - containerPort: 5044

      - name: filebeat
        image: mohamedsaeed/cognitive:filebeat
        # volumeMounts:
        #   - name: nginx_logs
        #     mountPath: /var/log/nginx/

      volumes:
        - name: nginx-logs
          emptyDir: {}

