apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  ports:
  - nodePort: 30500
    name: nginx
    port: 80
    protocol: TCP
    targetPort: 80
  - nodePort: 30501
    name: kibana
    port: 5601
    protocol: TCP
    targetPort: 5601
  - nodePort: 30502
    name: elasticsearch
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    app: nginx
  type: NodePort
